### ISSUE TITLE
🐞 BUG: 새로고침 시 설장한 컬러/다크&라이트 모드가 사라짐

### ISSUE THREAD

**Issue by hyowon2** [ds92ko/unit-mate#25]
## 📝 버그 설명

> 발생한 버그에 대한 간략한 설명

- 컬러값/다크&라이트 모드 변경 후 페이지 새로고침 시 설정값이 사라지고 있음

<br/>

## 🤔 기대 동작

> 기대했던 동작에 대한 설명

- 설정한 값이 그대로 유지되는 것을 생각함

<br/>

## 😯 실제 동작

> 실제로 발생한 동작 또는 에러 메시지

- 컬러값/다크&라이트 모드 변경 후 페이지 새로고침(F5) 시 설정한 값이 사라지고 있음

**Comment by ds92ko** [comment]
@hyowon2 해당 사항 로컬에서는 반영 됐는데 리뷰가 늦어져 아직 개발서버에 머지가 안된 상태입니다. 개발서버 반영 후 댓글 남길게요!

**Comment by ds92ko** [comment]
@hyowon2 해당 이슈 사항 개발서버에 반영하였습니다 확인 부탁드립니다

**Comment by hyowon2** [comment]
확인 완료
