### ISSUE TITLE
🐞 BUG: 강력 새고로침 시 404 에러 발생

### ISSUE THREAD

**Issue by hyowon2** [ds92ko/unit-mate#42]
## 📝 버그 설명

- basic 탭을 제외한 '모든 탭'에서 강력 새로고침 시 404 페이지가 호출되고 있습니다. 

## 📷 스크린샷

<img width="548" alt="image" src="https://github.com/ds92ko/unit-mate/assets/57744841/91795133-e9f9-4135-b517-b9ed4498249e">

**Comment by ds92ko** [comment]
@hyowon2 개발서버 반영 완료하였습니다

**Comment by hyowon2** [comment]
확인 완료
