### ISSUE TITLE
🐞 BUG: 북마크 6개 이상 시 스크롤 추가 요청

### ISSUE THREAD

**Issue by hyowon2** [ds92ko/unit-mate#81]
## 📝 버그 설명

> 발생한 버그에 대한 간략한 설명

- 북마크 6개 이상 등록 시 페이지 스크롤이 추가되지 않고 있음

<br/>

## 🤔 기대 동작

> 기대했던 동작에 대한 설명

- 북마크 영역 내 스크롤이 추가되어 북마크 리스트를 확인하는 것을 예상

<br/>

## 😯 실제 동작

> 실제로 발생한 동작 또는 에러 메시지

- 스크롤이 생기지 않아 북마크 리스트를 확인할 수 없음

<br/>

## 📷 스크린샷

<img width="1438" alt="스크린샷 2024-02-25 오후 6 36 34" src="https://github.com/ds92ko/unit-mate/assets/57744841/82988ab8-f934-4cb9-88bb-c5154cc2f7c6">

**Comment by rlacodud** [comment]
해당 이슈 아래 이슈에서 수정되어있는 걸로 압니다!
아직 배포가 안되어 동일한 이슈 발견되는 것 같습니다.
#61
